name: CI
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  statuses: write

jobs:
  checks:
    uses: muxu-io/python-template/.github/workflows/checks.yml@master
    with:
      python-versions: '["3.9", "3.10", "3.11", "3.12"]'
      source-directory: 'src/'
      enable-mqtt-broker: true
      mqtt-config-path: '.github/mosquitto.conf'

